/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardeal;

/**
 *
 * @author fpilo
 */
public class apothiki extends javax.swing.JFrame {

    /**
     * Creates new form apothiki
     */
    public apothiki() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        default_loggedIn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        epexergasia_profile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onoma_txt = new javax.swing.JTextField();
        eponimo_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        dief8insi_txt = new javax.swing.JTextField();
        ari8mos_txt = new javax.swing.JTextField();
        telephone_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Update_DB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diaxeirisi_paraggeliwn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        diaxeirisi_apothematos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        part_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        part_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        part_stock = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        part_new_stock = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        part_name2 = new javax.swing.JTextField();
        part_id2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        part_stock2 = new javax.swing.JTextField();
        part_new_stock2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        messages = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        send_new_message_btn = new javax.swing.JButton();
        new_message_txt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        leitourgies_axrhsto = new javax.swing.JMenu();
        diaxeirisi_parageliwn = new javax.swing.JMenuItem();
        stock_btn = new javax.swing.JMenuItem();
        diaxeirisi_stock = new javax.swing.JMenuItem();
        edit_profile_button = new javax.swing.JMenu();
        Logout_button = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        parent_panel.setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CarDeal - Αποθήκη");

        javax.swing.GroupLayout default_loggedInLayout = new javax.swing.GroupLayout(default_loggedIn);
        default_loggedIn.setLayout(default_loggedInLayout);
        default_loggedInLayout.setHorizontalGroup(
            default_loggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(default_loggedInLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        default_loggedInLayout.setVerticalGroup(
            default_loggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(default_loggedInLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        parent_panel.add(default_loggedIn, "card3");

        epexergasia_profile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        epexergasia_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        epexergasia_profile.setEnabled(false);
        epexergasia_profile.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                epexergasia_profileComponentAdded(evt);
            }
        });

        onoma_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoma_txtActionPerformed(evt);
            }
        });

        dief8insi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dief8insi_txtActionPerformed(evt);
            }
        });

        jLabel1.setText("Όνομα");

        jLabel3.setText("Επώνυμο");

        jLabel4.setText("Email");

        Update_DB.setText("Αποθήκευση");
        Update_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_DBActionPerformed(evt);
            }
        });

        jLabel5.setText("Διεύθυνση");

        jLabel6.setText("Αριθμός");

        jLabel7.setText("Τηλέφωνο");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Επεξεργασία Προφίλ");

        javax.swing.GroupLayout epexergasia_profileLayout = new javax.swing.GroupLayout(epexergasia_profile);
        epexergasia_profile.setLayout(epexergasia_profileLayout);
        epexergasia_profileLayout.setHorizontalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Update_DB)
                            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(40, 40, 40)
                                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(email_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(eponimo_txt)
                                    .addComponent(onoma_txt))
                                .addGap(105, 105, 105))))
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGap(39, 39, 39)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(dief8insi_txt)
                    .addComponent(telephone_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        epexergasia_profileLayout.setVerticalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel8)
                .addGap(93, 93, 93)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dief8insi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eponimo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(telephone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(Update_DB)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        parent_panel.add(epexergasia_profile, "card2");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Διαχείριση παραγγελιών");

        javax.swing.GroupLayout diaxeirisi_paraggeliwnLayout = new javax.swing.GroupLayout(diaxeirisi_paraggeliwn);
        diaxeirisi_paraggeliwn.setLayout(diaxeirisi_paraggeliwnLayout);
        diaxeirisi_paraggeliwnLayout.setHorizontalGroup(
            diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                .addGap(509, 509, 509)
                .addComponent(jLabel13)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        diaxeirisi_paraggeliwnLayout.setVerticalGroup(
            diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel13)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        parent_panel.add(diaxeirisi_paraggeliwn, "card4");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Διαχείριση αποθέματος");

        jTextField1.setText("Εισάγετε κωδικό ανταλλακτικού");

        jButton1.setText("Αναζήτηση");

        part_name.setEditable(false);
        part_name.setFocusable(false);

        jLabel10.setText("Είδος");

        part_id.setEditable(false);
        part_id.setText("5");
        part_id.setEnabled(false);

        jLabel11.setText("Κωδικός");

        part_stock.setEditable(false);
        part_stock.setFocusable(false);

        jLabel12.setText("Διαθεσιμότητα");

        jLabel16.setText("Επιπλέον ποσότητα");

        jButton2.setText("Προσθήκη stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Είδος");

        part_name2.setEditable(false);
        part_name2.setFocusable(false);

        part_id2.setEditable(false);
        part_id2.setText("5");
        part_id2.setEnabled(false);

        jLabel22.setText("Κωδικός");

        jLabel23.setText("Διαθεσιμότητα");

        part_stock2.setEditable(false);
        part_stock2.setFocusable(false);

        jLabel24.setText("Αφαίρεση ποσότητα");

        jButton4.setText("Αφαίρεση stock");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaxeirisi_apothematosLayout = new javax.swing.GroupLayout(diaxeirisi_apothematos);
        diaxeirisi_apothematos.setLayout(diaxeirisi_apothematosLayout);
        diaxeirisi_apothematosLayout.setHorizontalGroup(
            diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(part_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(part_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(part_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(60, 60, 60)
                                .addComponent(part_new_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                            .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(part_id2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(part_name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(part_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(60, 60, 60)
                            .addComponent(part_new_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton4)))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_apothematosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(515, 515, 515))
        );
        diaxeirisi_apothematosLayout.setVerticalGroup(
            diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel15)
                .addGap(59, 59, 59)
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(83, 83, 83)
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_new_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(55, 55, 55)
                        .addComponent(jButton2))
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_new_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(55, 55, 55)
                        .addComponent(jButton4)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        parent_panel.add(diaxeirisi_apothematos, "card6");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Μηνύματα");

        send_new_message_btn.setText("Αποστολή");

        new_message_txt.setText("Πληκτρολογήστε νέο μήνυμα");
        new_message_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_message_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messagesLayout = new javax.swing.GroupLayout(messages);
        messages.setLayout(messagesLayout);
        messagesLayout.setHorizontalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesLayout.createSequentialGroup()
                .addGap(597, 597, 597)
                .addComponent(jLabel14)
                .addGap(0, 652, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagesLayout.createSequentialGroup()
                        .addComponent(send_new_message_btn)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagesLayout.createSequentialGroup()
                        .addComponent(new_message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        messagesLayout.setVerticalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel14)
                .addGap(92, 92, 92)
                .addComponent(new_message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(send_new_message_btn)
                .addGap(97, 97, 97))
        );

        parent_panel.add(messages, "card5");

        leitourgies_axrhsto.setText("Λειτουργίες");
        leitourgies_axrhsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leitourgies_axrhstoActionPerformed(evt);
            }
        });

        diaxeirisi_parageliwn.setText("Διαχείριση παραγγελιών");
        diaxeirisi_parageliwn.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                diaxeirisi_parageliwnMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        diaxeirisi_parageliwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diaxeirisi_parageliwnMouseClicked(evt);
            }
        });
        diaxeirisi_parageliwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaxeirisi_parageliwnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(diaxeirisi_parageliwn);

        stock_btn.setText("Μηνύματα");
        stock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(stock_btn);

        diaxeirisi_stock.setText("Διαχείριση αποθέματος");
        diaxeirisi_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaxeirisi_stockActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(diaxeirisi_stock);

        jMenuBar1.add(leitourgies_axrhsto);

        edit_profile_button.setText("Επεξεργασία προφιλ");
        edit_profile_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                edit_profile_buttonMenuSelected(evt);
            }
        });
        edit_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(edit_profile_button);

        Logout_button.setText("Αποσύνδεση");
        Logout_button.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                Logout_buttonMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        Logout_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Logout_buttonMenuSelected(evt);
            }
        });
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(Logout_button);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void close() { 
    this.setVisible(false); // FUNCTION GIA KLEISIMO PARA8IROU
    this.dispose();
}
    private void diaxeirisi_parageliwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaxeirisi_parageliwnActionPerformed
       parent_panel.removeAll();
       parent_panel.add(diaxeirisi_paraggeliwn);
       parent_panel.repaint();
       parent_panel.revalidate();
    }//GEN-LAST:event_diaxeirisi_parageliwnActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        Login Lg = new Login();
       Lg.setVisible(true);
       Lg.pack();
       Lg.setLocationRelativeTo(null);
       Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
       close();
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void edit_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile_buttonActionPerformed

    private void Logout_buttonMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_Logout_buttonMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_buttonMenuKeyPressed

    private void Logout_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Logout_buttonMenuSelected
           Login Lg = new Login();
       Lg.setVisible(true);
       Lg.pack();
       Lg.setLocationRelativeTo(null);
       Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
       close();
    }//GEN-LAST:event_Logout_buttonMenuSelected

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        epexergasia_profile.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void edit_profile_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_edit_profile_buttonMenuSelected
       parent_panel.removeAll();
       parent_panel.add(epexergasia_profile);
       parent_panel.repaint();
       parent_panel.revalidate();
    }//GEN-LAST:event_edit_profile_buttonMenuSelected

    private void diaxeirisi_parageliwnMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_diaxeirisi_parageliwnMenuKeyPressed

    }//GEN-LAST:event_diaxeirisi_parageliwnMenuKeyPressed

    private void leitourgies_axrhstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leitourgies_axrhstoActionPerformed

    }//GEN-LAST:event_leitourgies_axrhstoActionPerformed

    private void diaxeirisi_parageliwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diaxeirisi_parageliwnMouseClicked

    }//GEN-LAST:event_diaxeirisi_parageliwnMouseClicked

    private void stock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_btnActionPerformed
       parent_panel.removeAll();
       parent_panel.add(messages);
       parent_panel.repaint();
       parent_panel.revalidate();
    }//GEN-LAST:event_stock_btnActionPerformed

    private void diaxeirisi_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaxeirisi_stockActionPerformed
       parent_panel.removeAll();
       parent_panel.add(diaxeirisi_apothematos);
       parent_panel.repaint();
       parent_panel.revalidate();
    }//GEN-LAST:event_diaxeirisi_stockActionPerformed

    private void epexergasia_profileComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_epexergasia_profileComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_epexergasia_profileComponentAdded

    private void Update_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_DBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_DBActionPerformed

    private void dief8insi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dief8insi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dief8insi_txtActionPerformed

    private void onoma_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoma_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onoma_txtActionPerformed

    private void new_message_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_message_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_message_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apothiki().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout_button;
    private javax.swing.JButton Update_DB;
    private javax.swing.JTextField ari8mos_txt;
    private javax.swing.JPanel default_loggedIn;
    private javax.swing.JPanel diaxeirisi_apothematos;
    private javax.swing.JMenuItem diaxeirisi_parageliwn;
    private javax.swing.JPanel diaxeirisi_paraggeliwn;
    private javax.swing.JMenuItem diaxeirisi_stock;
    private javax.swing.JTextField dief8insi_txt;
    private javax.swing.JMenu edit_profile_button;
    private javax.swing.JTextField email_txt;
    private javax.swing.JPanel epexergasia_profile;
    private javax.swing.JTextField eponimo_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenu leitourgies_axrhsto;
    private javax.swing.JPanel messages;
    private javax.swing.JTextField new_message_txt;
    private javax.swing.JTextField onoma_txt;
    private javax.swing.JPanel parent_panel;
    private javax.swing.JTextField part_id;
    private javax.swing.JTextField part_id2;
    private javax.swing.JTextField part_name;
    private javax.swing.JTextField part_name2;
    private javax.swing.JTextField part_new_stock;
    private javax.swing.JTextField part_new_stock2;
    private javax.swing.JTextField part_stock;
    private javax.swing.JTextField part_stock2;
    private javax.swing.JButton send_new_message_btn;
    private javax.swing.JMenuItem stock_btn;
    private javax.swing.JTextField telephone_txt;
    // End of variables declaration//GEN-END:variables
}
