/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardeal;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class apothiki extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs =null;
PreparedStatement pst=null;
    /**
     * Creates new form apothiki
     */
    public apothiki() {
        initComponents();
        conn = connect.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        default_loggedIn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        epexergasia_profile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onoma_txt = new javax.swing.JTextField();
        eponimo_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        dief8insi_txt = new javax.swing.JTextField();
        ari8mos_txt = new javax.swing.JTextField();
        telephone_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Update_DB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diaxeirisi_paraggeliwn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        id_paragelias_txt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        c_first_name_txt = new javax.swing.JTextField();
        c_last_name_txt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        c_email_txt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        status_txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        date_txt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        save_packing_progress_btn = new javax.swing.JButton();
        finish_packing_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paraggelies_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        products_orderedWstock_table = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        stock_txt = new javax.swing.JTextField();
        diaxeirisi_apothematos = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        search_id_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        part_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        part_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        part_stock = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        part_new_stock = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        prosthiki_stock_btn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        part_name2 = new javax.swing.JTextField();
        part_id2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        part_stock2 = new javax.swing.JTextField();
        part_new_stock2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        afairesh_stock_btn = new javax.swing.JButton();
        messages = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        send_new_message_btn = new javax.swing.JButton();
        new_message_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_show = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        messages_btn = new javax.swing.JMenu();
        diaxeirisi_parageliwn = new javax.swing.JMenuItem();
        stock_btn = new javax.swing.JMenuItem();
        diaxeirisi_stock = new javax.swing.JMenuItem();
        edit_profile_button = new javax.swing.JMenu();
        Logout_button = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarDeal by P.B. C. D. A. G. & G. L.");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        parent_panel.setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CarDeal - Αποθήκη");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardeal/logo_200x200.png"))); // NOI18N

        javax.swing.GroupLayout default_loggedInLayout = new javax.swing.GroupLayout(default_loggedIn);
        default_loggedIn.setLayout(default_loggedInLayout);
        default_loggedInLayout.setHorizontalGroup(
            default_loggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(default_loggedInLayout.createSequentialGroup()
                .addGroup(default_loggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(default_loggedInLayout.createSequentialGroup()
                        .addGap(448, 448, 448)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(default_loggedInLayout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(jLabel17)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        default_loggedInLayout.setVerticalGroup(
            default_loggedInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, default_loggedInLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(182, 182, 182))
        );

        parent_panel.add(default_loggedIn, "card3");

        epexergasia_profile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        epexergasia_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        epexergasia_profile.setEnabled(false);
        epexergasia_profile.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                epexergasia_profileComponentAdded(evt);
            }
        });

        onoma_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoma_txtActionPerformed(evt);
            }
        });

        dief8insi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dief8insi_txtActionPerformed(evt);
            }
        });

        jLabel1.setText("Όνομα");

        jLabel3.setText("Επώνυμο");

        jLabel4.setText("Email");

        Update_DB.setText("Αποθήκευση");
        Update_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_DBActionPerformed(evt);
            }
        });

        jLabel5.setText("Διεύθυνση");

        jLabel6.setText("Αριθμός");

        jLabel7.setText("Τηλέφωνο");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Επεξεργασία Προφίλ");

        javax.swing.GroupLayout epexergasia_profileLayout = new javax.swing.GroupLayout(epexergasia_profile);
        epexergasia_profile.setLayout(epexergasia_profileLayout);
        epexergasia_profileLayout.setHorizontalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Update_DB)
                            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(40, 40, 40)
                                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(email_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(eponimo_txt)
                                    .addComponent(onoma_txt))
                                .addGap(105, 105, 105))))
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGap(39, 39, 39)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(dief8insi_txt)
                    .addComponent(telephone_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        epexergasia_profileLayout.setVerticalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel8)
                .addGap(93, 93, 93)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dief8insi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)))
                .addGap(26, 26, 26)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(telephone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(Update_DB)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        parent_panel.add(epexergasia_profile, "card2");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Διαχείριση παραγγελιών");

        jLabel19.setText("Αρ. επιλεγμένης παραγγελίας");

        id_paragelias_txt.setEditable(false);
        id_paragelias_txt.setEnabled(false);
        id_paragelias_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_paragelias_txtActionPerformed(evt);
            }
        });

        jLabel20.setText("Όνομα");

        jLabel25.setText("Επώνυμο");

        c_first_name_txt.setEditable(false);
        c_first_name_txt.setEnabled(false);

        c_last_name_txt.setEditable(false);
        c_last_name_txt.setEnabled(false);

        jLabel27.setText("email");

        c_email_txt.setEditable(false);
        c_email_txt.setEnabled(false);

        jLabel28.setText("Κατάσταση");

        status_txt.setEditable(false);
        status_txt.setEnabled(false);

        jLabel18.setText("Ημερομηνία");

        date_txt.setEditable(false);
        date_txt.setEnabled(false);

        jLabel26.setText("Παραγγελίες");

        save_packing_progress_btn.setText("Συσκευασία επιλεγμένων προϊόντων");
        save_packing_progress_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_packing_progress_btnActionPerformed(evt);
            }
        });

        finish_packing_btn.setText("Ολοκλήρωση συσκευασίας");
        finish_packing_btn.setToolTipText("");
        finish_packing_btn.setEnabled(false);
        finish_packing_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_packing_btnActionPerformed(evt);
            }
        });

        jButton3.setText("Ακύρωση παραγγελίας");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel29.setText("Παραγγελθέντα προιόντα");

        paraggelies_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        paraggelies_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paraggelies_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(paraggelies_table);

        products_orderedWstock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        products_orderedWstock_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                products_orderedWstock_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(products_orderedWstock_table);

        jLabel30.setText("Διαθέσιμα");

        stock_txt.setEditable(false);
        stock_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stock_txt.setEnabled(false);

        javax.swing.GroupLayout diaxeirisi_paraggeliwnLayout = new javax.swing.GroupLayout(diaxeirisi_paraggeliwn);
        diaxeirisi_paraggeliwn.setLayout(diaxeirisi_paraggeliwnLayout);
        diaxeirisi_paraggeliwnLayout.setHorizontalGroup(
            diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel26)))
                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(finish_packing_btn)
                                .addGap(18, 18, 18)
                                .addComponent(save_packing_progress_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel30))
                                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(stock_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59))))
                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel29))
                            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(c_first_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c_email_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56)
                                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18))
                                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                        .addComponent(id_paragelias_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)))
                                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(status_txt)
                                    .addComponent(c_last_name_txt)
                                    .addComponent(date_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diaxeirisi_paraggeliwnLayout.setVerticalGroup(
            diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(49, 49, 49)
                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(id_paragelias_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(status_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(c_first_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(c_last_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel18)
                            .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel29)
                        .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(diaxeirisi_paraggeliwnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(save_packing_progress_btn)
                                    .addComponent(finish_packing_btn)
                                    .addComponent(jButton3))
                                .addGap(27, 27, 27))
                            .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stock_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(diaxeirisi_paraggeliwnLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        parent_panel.add(diaxeirisi_paraggeliwn, "card4");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Διαχείριση αποθέματος");

        search_id_txt.setText("Εισάγετε κωδικό ανταλλακτικού");

        search_btn.setText("Αναζήτηση");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        part_name.setEditable(false);
        part_name.setFocusable(false);

        jLabel10.setText("Είδος");

        part_id.setEditable(false);
        part_id.setEnabled(false);

        jLabel11.setText("Κωδικός");

        part_stock.setEditable(false);
        part_stock.setFocusable(false);

        jLabel12.setText("Διαθεσιμότητα");

        jLabel16.setText("Προσθήκη ποσότητας");

        prosthiki_stock_btn.setText("Προσθήκη stock");
        prosthiki_stock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosthiki_stock_btnActionPerformed(evt);
            }
        });

        jLabel21.setText("Είδος");

        part_name2.setEditable(false);
        part_name2.setFocusable(false);

        part_id2.setEditable(false);
        part_id2.setEnabled(false);

        jLabel22.setText("Κωδικός");

        jLabel23.setText("Διαθεσιμότητα");

        part_stock2.setEditable(false);
        part_stock2.setFocusable(false);

        jLabel24.setText("Αφαίρεσης ποσότητας");

        afairesh_stock_btn.setText("Αφαίρεση stock");
        afairesh_stock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afairesh_stock_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaxeirisi_apothematosLayout = new javax.swing.GroupLayout(diaxeirisi_apothematos);
        diaxeirisi_apothematos.setLayout(diaxeirisi_apothematosLayout);
        diaxeirisi_apothematosLayout.setHorizontalGroup(
            diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(part_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(part_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(part_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(60, 60, 60)
                                .addComponent(part_new_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(prosthiki_stock_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                            .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(part_id2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(part_name2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(part_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(60, 60, 60)
                            .addComponent(part_new_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(afairesh_stock_btn)))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGap(622, 622, 622)
                .addComponent(search_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(search_btn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGap(604, 604, 604)
                .addComponent(jLabel15)
                .addGap(515, 515, 515))
        );
        diaxeirisi_apothematosLayout.setVerticalGroup(
            diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel15)
                .addGap(50, 50, 50)
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn))
                .addGap(92, 92, 92)
                .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(part_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_new_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(55, 55, 55)
                        .addComponent(prosthiki_stock_btn))
                    .addGroup(diaxeirisi_apothematosLayout.createSequentialGroup()
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(part_id2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(diaxeirisi_apothematosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(part_new_stock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(55, 55, 55)
                        .addComponent(afairesh_stock_btn)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        parent_panel.add(diaxeirisi_apothematos, "card6");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Μηνύματα");

        send_new_message_btn.setText("Αποστολή");
        send_new_message_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_new_message_btnActionPerformed(evt);
            }
        });

        new_message_txt.setText("Πληκτρολογήστε νέο μήνυμα");
        new_message_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_message_txtActionPerformed(evt);
            }
        });

        Table_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_show);

        javax.swing.GroupLayout messagesLayout = new javax.swing.GroupLayout(messages);
        messages.setLayout(messagesLayout);
        messagesLayout.setHorizontalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagesLayout.createSequentialGroup()
                .addGroup(messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagesLayout.createSequentialGroup()
                        .addContainerGap(656, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane1))
                .addGroup(messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagesLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(send_new_message_btn))
                    .addGroup(messagesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(new_message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        messagesLayout.setVerticalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(send_new_message_btn)
                .addGap(88, 88, 88))
            .addGroup(messagesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel14)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );

        parent_panel.add(messages, "card5");

        messages_btn.setText("Λειτουργίες");
        messages_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messages_btnActionPerformed(evt);
            }
        });

        diaxeirisi_parageliwn.setText("Διαχείριση παραγγελιών");
        diaxeirisi_parageliwn.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                diaxeirisi_parageliwnMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        diaxeirisi_parageliwn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diaxeirisi_parageliwnMouseClicked(evt);
            }
        });
        diaxeirisi_parageliwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaxeirisi_parageliwnActionPerformed(evt);
            }
        });
        messages_btn.add(diaxeirisi_parageliwn);

        stock_btn.setText("Μηνύματα");
        stock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_btnActionPerformed(evt);
            }
        });
        messages_btn.add(stock_btn);

        diaxeirisi_stock.setText("Διαχείριση αποθέματος");
        diaxeirisi_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaxeirisi_stockActionPerformed(evt);
            }
        });
        messages_btn.add(diaxeirisi_stock);

        jMenuBar1.add(messages_btn);

        edit_profile_button.setText("Επεξεργασία προφιλ");
        edit_profile_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                edit_profile_buttonMenuSelected(evt);
            }
        });
        edit_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(edit_profile_button);

        Logout_button.setText("Αποσύνδεση");
        Logout_button.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                Logout_buttonMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        Logout_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Logout_buttonMenuSelected(evt);
            }
        });
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(Logout_button);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void close() { 
    this.setVisible(false); // FUNCTION GIA KLEISIMO PARA8IROU
    this.dispose();
}
 private void loadUserProfile() {
    String username = Session.getUsername();
    try {
        String sql = "SELECT FirstName, LastName, Email, Street, StreetNum, Telephone FROM User WHERE Username = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            onoma_txt.setText(rs.getString("FirstName"));
            eponimo_txt.setText(rs.getString("LastName"));
            email_txt.setText(rs.getString("Email"));
            dief8insi_txt.setText(rs.getString("Street"));
            ari8mos_txt.setText(rs.getString("StreetNum"));
            telephone_txt.setText(rs.getString("Telephone"));
        }
        rs.close();
        pst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
}
 private void Update_Table(String tablename){
   
        try {
                  String sql = "SELECT * FROM " + tablename ;
                  pst=conn.prepareStatement(sql);
                  rs=pst.executeQuery();
                    Table_show.setModel(DbUtils.resultSetToTableModel(rs));
              } catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);}
}
 
 private void updateStockFields(){
    try{
        String SelectQ = "SELECT Quantity FROM Product WHERE ProductID = ?";
        pst = conn.prepareStatement(SelectQ);
        pst.setString(1, search_id_txt.getText());
        ResultSet rs = pst.executeQuery();
        
        if(rs.next()){ 
            part_stock.setText(String.valueOf(rs.getInt("Quantity")));
            part_stock2.setText(String.valueOf(rs.getInt("Quantity")));
        }        
    } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null,ex);}
 }
    private void diaxeirisi_parageliwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaxeirisi_parageliwnActionPerformed
       parent_panel.removeAll();
       parent_panel.add(diaxeirisi_paraggeliwn);
       parent_panel.repaint();
       parent_panel.revalidate();
       
        try {
            String sql = "SELECT OrderID, CustomerName, Sub_date, Status_ FROM Order_";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            paraggelies_table.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);}  
    }//GEN-LAST:event_diaxeirisi_parageliwnActionPerformed

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
       Login Lg = new Login();
       Lg.setVisible(true);
       Lg.pack();
       Lg.setLocationRelativeTo(null);
       Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
       close(); // axristooooo
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void edit_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile_buttonActionPerformed

    private void Logout_buttonMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_Logout_buttonMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_buttonMenuKeyPressed

    private void Logout_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Logout_buttonMenuSelected
       Login Lg = new Login();
       Lg.setVisible(true);
       Lg.pack();
       Lg.setLocationRelativeTo(null);
       Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
       close();
    }//GEN-LAST:event_Logout_buttonMenuSelected

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        epexergasia_profile.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void edit_profile_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_edit_profile_buttonMenuSelected
       parent_panel.removeAll();
       parent_panel.add(epexergasia_profile);
       parent_panel.repaint();
       parent_panel.revalidate();
       loadUserProfile();
       String username = Session.getUsername();
 
    }//GEN-LAST:event_edit_profile_buttonMenuSelected

    private void diaxeirisi_parageliwnMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_diaxeirisi_parageliwnMenuKeyPressed

    }//GEN-LAST:event_diaxeirisi_parageliwnMenuKeyPressed

    private void messages_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messages_btnActionPerformed

    }//GEN-LAST:event_messages_btnActionPerformed

    private void diaxeirisi_parageliwnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diaxeirisi_parageliwnMouseClicked

    }//GEN-LAST:event_diaxeirisi_parageliwnMouseClicked

    private void stock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_btnActionPerformed
       parent_panel.removeAll();
       parent_panel.add(messages);
       parent_panel.repaint();
       parent_panel.revalidate();
      Update_Table("Messages");
    }//GEN-LAST:event_stock_btnActionPerformed

    private void diaxeirisi_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaxeirisi_stockActionPerformed
       parent_panel.removeAll();
       parent_panel.add(diaxeirisi_apothematos);
       parent_panel.repaint();
       parent_panel.revalidate();
    }//GEN-LAST:event_diaxeirisi_stockActionPerformed

    private void epexergasia_profileComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_epexergasia_profileComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_epexergasia_profileComponentAdded

    private void Update_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_DBActionPerformed
             String username = Session.getUsername();                           
        try{
            String value1= onoma_txt.getText();
            String value2= eponimo_txt.getText();
            String value3= email_txt.getText();
            String value4= dief8insi_txt.getText();
            String value5= ari8mos_txt.getText();
            String value6= telephone_txt.getText();
            String sql ="UPDATE  User set FirstName = ?, LastName=?, email=?, Telephone=?, Street=?, StreetNum=? WHERE Username=? ";
            pst=conn.prepareStatement(sql);
            pst.setString(1, value1);
            pst.setString(2, value2);
            pst.setString(3, value3);
            pst.setString(4, value6);
            pst.setString(5, value4);
            pst.setString(6, value5);
            pst.setString(7, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data updated succesfully");
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);}
       
     
    }//GEN-LAST:event_Update_DBActionPerformed

    private void dief8insi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dief8insi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dief8insi_txtActionPerformed

    private void onoma_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoma_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onoma_txtActionPerformed

    private void new_message_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_message_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_message_txtActionPerformed

    private void prosthiki_stock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosthiki_stock_btnActionPerformed
        try{
            String posothta_to_add_str = part_new_stock.getText().trim();
            int posothta_to_add = Integer.parseInt(posothta_to_add_str);

            if(posothta_to_add <= 0 ){
                JOptionPane.showMessageDialog(null, "Δεν μπορεί να προστεθεί μηδενική ποσότητα.");
                return;
            }

            String SelectQ = "SELECT Quantity FROM Product WHERE ProductID = ?";
            pst = conn.prepareStatement(SelectQ);
            pst.setString(1, search_id_txt.getText());
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                int current_quantity = rs.getInt("Quantity");
                int new_quantity = current_quantity + posothta_to_add;
                rs.close();
                pst.close();

                String UpdateQ = "UPDATE Product SET Quantity = ? WHERE ProductID = ?";
                pst = conn.prepareStatement(UpdateQ);
                pst.setInt(1, new_quantity);
                pst.setString(2, search_id_txt.getText());

                pst.executeUpdate();
                pst.close();

                updateStockFields();
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);}     
    }//GEN-LAST:event_prosthiki_stock_btnActionPerformed

    private void afairesh_stock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afairesh_stock_btnActionPerformed
        try{
            String posothta_to_add_str = part_new_stock.getText().trim();
            int posothta_to_remove = Integer.parseInt(posothta_to_add_str);

            if(posothta_to_remove <= 0 ){
                JOptionPane.showMessageDialog(null, "Δεν μπορεί να αφαιρεθεί μηδενική ποσότητα.");
                return;
            }

            String SelectQ = "SELECT Quantity FROM Product WHERE ProductID = ?";
            pst = conn.prepareStatement(SelectQ);
            pst.setString(1, search_id_txt.getText());
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                int current_quantity = rs.getInt("Quantity");
                int new_quantity = current_quantity - posothta_to_remove;
                rs.close();
                pst.close();

                String UpdateQ = "UPDATE Product SET Quantity = ? WHERE ProductID = ?";
                pst = conn.prepareStatement(UpdateQ);
                pst.setInt(1, new_quantity);
                pst.setString(2, search_id_txt.getText());

                pst.executeUpdate();
                pst.close();

                updateStockFields();
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);}  
    }//GEN-LAST:event_afairesh_stock_btnActionPerformed

    private void id_paragelias_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_paragelias_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_paragelias_txtActionPerformed

    private void save_packing_progress_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_packing_progress_btnActionPerformed
        int row = paraggelies_table.getSelectedRow();
        int row2 = products_orderedWstock_table.getSelectedRow();
        
               
        String id_paraggelias = paraggelies_table.getModel().getValueAt(row,0).toString();
        
        String prod_id = products_orderedWstock_table.getModel().getValueAt(row2,0).toString();
        int id_product = Integer.parseInt(prod_id);
        
        String prod_or_quan = products_orderedWstock_table.getModel().getValueAt(row2,1).toString();
        int product_order_quantity = Integer.parseInt(prod_or_quan);
        
        String cu_st = stock_txt.getText();
        int curr_stock = Integer.parseInt(cu_st);
        
        int new_stock = curr_stock;
        
        if(product_order_quantity > curr_stock){
            JOptionPane.showMessageDialog(null,"Ανεπαρκής ποσότητα στην αποθήκη");
        }else{
            new_stock = curr_stock - product_order_quantity;
        }
                
                
        try{
            String sqlRemoveStock = "UPDATE Product SET Quantity = ? WHERE ProductID = ?";
            PreparedStatement pstStock = conn.prepareStatement(sqlRemoveStock);
            pstStock.setInt(1, new_stock);
            pstStock.setInt(2, id_product);
            pstStock.executeUpdate();
            
            String sqlUpdate = "UPDATE Package SET PackageStatus = 'Packed' WHERE PackageID = ?";
            PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
            pstUpdate.setString(1, id_paraggelias);
            pstUpdate.executeUpdate();
            JOptionPane.showMessageDialog(null,"Το προιόν θεωρείται συσκευασμένο.");
            stock_txt.setText(String.valueOf(new_stock));
            finish_packing_btn.setEnabled(true);
            
        }catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);}     
    }//GEN-LAST:event_save_packing_progress_btnActionPerformed

    private void send_new_message_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_new_message_btnActionPerformed
        String username = Session.getUsername();
        try{
            String sql ="INSERT INTO Messages (MessageText, SenderName) VALUES (?, ?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, new_message_txt.getText());
            pst.setString(2, username);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Message Sent Succesfully!");
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);}
        Update_Table("Messages");
    }//GEN-LAST:event_send_new_message_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        try{
            String sql = "SELECT ProductName, Price, Quantity FROM Product WHERE ProductID = ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, search_id_txt.getText());
            
            pst.execute();
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                part_name.setText(rs.getString("ProductName"));
                part_id.setText(search_id_txt.getText());
                part_stock.setText(rs.getString("Quantity"));
                
                part_name2.setText(rs.getString("ProductName"));
                part_id2.setText(search_id_txt.getText());
                part_stock2.setText(rs.getString("Quantity"));     
            }
            
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);}
    }//GEN-LAST:event_search_btnActionPerformed

    private void paraggelies_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraggelies_tableMouseClicked
        int row = paraggelies_table.getSelectedRow();
        String customer_uname = paraggelies_table.getModel().getValueAt(row,1).toString();
        String id_paraggelias = paraggelies_table.getModel().getValueAt(row,0).toString();
        
        try{ //plhrofories paraggelias
            String SelectCustomerData = "SELECT FirstName, LastName, Email FROM User WHERE Username = ?";
            pst=conn.prepareStatement(SelectCustomerData);
            pst.setString(1,customer_uname);
            rs=pst.executeQuery(); 
            if(rs.next()){
                String add1 =rs.getString("FirstName");
                c_first_name_txt.setText(add1);
                String add2 =rs.getString("LastName");
                c_last_name_txt.setText(add2); 
                String add3 =rs.getString("Email");
                c_email_txt.setText(add3); 
            }
            rs.close();
            pst.close();
            
            id_paragelias_txt.setText(id_paraggelias);
            date_txt.setText(paraggelies_table.getModel().getValueAt(row,2).toString());
            status_txt.setText(paraggelies_table.getModel().getValueAt(row,3).toString());           
        } catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);}  
        
        try{ //proionta
            String sql = "SELECT ProductID, Quantity FROM Order_ WHERE OrderID = ?";
            PreparedStatement pst2 = conn.prepareStatement(sql);
            pst2.setString(1, id_paraggelias);
            ResultSet rs2 = pst2.executeQuery();
            products_orderedWstock_table.setModel(DbUtils.resultSetToTableModel(rs2));
        } catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);} 
    }//GEN-LAST:event_paraggelies_tableMouseClicked

    private void products_orderedWstock_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_products_orderedWstock_tableMouseClicked
        int row = products_orderedWstock_table.getSelectedRow();
        String product_selected_id = (products_orderedWstock_table.getModel().getValueAt(row,0).toString());
        
        try{
            String SelectStock = "SELECT Quantity FROM Product WHERE ProductID = ?";
            pst=conn.prepareStatement(SelectStock);
            pst.setString(1, product_selected_id);
            rs=pst.executeQuery(); 
            if(rs.next()){
                String add1 =rs.getString("Quantity");
                stock_txt.setText(add1);
            } 
        }catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);} 
    }//GEN-LAST:event_products_orderedWstock_tableMouseClicked

    private void finish_packing_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_packing_btnActionPerformed
        int row = paraggelies_table.getSelectedRow();
        String id_paraggelias = paraggelies_table.getModel().getValueAt(row,0).toString();
        String stat = "Ready for Pickup";
        
        try{
            String sqlUpdateOrderStatus = "UPDATE Order_ SET Status = ? WHERE OrderID = ?";
            PreparedStatement pstOrSt = conn.prepareStatement(sqlUpdateOrderStatus);
            pstOrSt.setString(1, stat);
            pstOrSt.setString(2, id_paraggelias);
            pstOrSt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Η παραγγελία άλλαξε κατάσταση σε 'Έτοιμη για παραλαβή'.");
            
        }catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);}   
    }//GEN-LAST:event_finish_packing_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = paraggelies_table.getSelectedRow();
        String id_paraggelias = paraggelies_table.getModel().getValueAt(row,0).toString();
        String stat = "Cancelled";
        
        try{
            String sqlUpdateOrderStatus = "UPDATE Order_ SET Status = ? WHERE OrderID = ?";
            PreparedStatement pstOrSt = conn.prepareStatement(sqlUpdateOrderStatus);
            pstOrSt.setString(1, stat);
            pstOrSt.setString(2, id_paraggelias);
            pstOrSt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Η παραγγελία ακυρώθηκε.");
            
        }catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);} 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apothiki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apothiki().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout_button;
    private javax.swing.JTable Table_show;
    private javax.swing.JButton Update_DB;
    private javax.swing.JButton afairesh_stock_btn;
    private javax.swing.JTextField ari8mos_txt;
    private javax.swing.JTextField c_email_txt;
    private javax.swing.JTextField c_first_name_txt;
    private javax.swing.JTextField c_last_name_txt;
    private javax.swing.JTextField date_txt;
    private javax.swing.JPanel default_loggedIn;
    private javax.swing.JPanel diaxeirisi_apothematos;
    private javax.swing.JMenuItem diaxeirisi_parageliwn;
    private javax.swing.JPanel diaxeirisi_paraggeliwn;
    private javax.swing.JMenuItem diaxeirisi_stock;
    private javax.swing.JTextField dief8insi_txt;
    private javax.swing.JMenu edit_profile_button;
    private javax.swing.JTextField email_txt;
    private javax.swing.JPanel epexergasia_profile;
    private javax.swing.JTextField eponimo_txt;
    private javax.swing.JButton finish_packing_btn;
    private javax.swing.JTextField id_paragelias_txt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel messages;
    private javax.swing.JMenu messages_btn;
    private javax.swing.JTextField new_message_txt;
    private javax.swing.JTextField onoma_txt;
    private javax.swing.JTable paraggelies_table;
    private javax.swing.JPanel parent_panel;
    private javax.swing.JTextField part_id;
    private javax.swing.JTextField part_id2;
    private javax.swing.JTextField part_name;
    private javax.swing.JTextField part_name2;
    private javax.swing.JTextField part_new_stock;
    private javax.swing.JTextField part_new_stock2;
    private javax.swing.JTextField part_stock;
    private javax.swing.JTextField part_stock2;
    private javax.swing.JTable products_orderedWstock_table;
    private javax.swing.JButton prosthiki_stock_btn;
    private javax.swing.JButton save_packing_progress_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_id_txt;
    private javax.swing.JButton send_new_message_btn;
    private javax.swing.JTextField status_txt;
    private javax.swing.JMenuItem stock_btn;
    private javax.swing.JTextField stock_txt;
    private javax.swing.JTextField telephone_txt;
    // End of variables declaration//GEN-END:variables
}
