/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardeal;
import java.sql.*;
import javax.swing.*;

public class customer extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs =null;
PreparedStatement pst=null;
    /**
     * Creates new form customer
     */
    public customer() {
         initComponents();
        conn = connect.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        epexergasia_profile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onoma_txt = new javax.swing.JTextField();
        eponimo_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        dief8insi_txt = new javax.swing.JTextField();
        ari8mos_txt = new javax.swing.JTextField();
        telephone_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Update_DB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        shop = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        wishlist_info_txt1 = new javax.swing.JTextField();
        wishlist_price_txt1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        wishlist_info_txt2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        wishlist_table1 = new javax.swing.JTable();
        rent = new javax.swing.JPanel();
        trade_in = new javax.swing.JPanel();
        wishlist = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        wishlist_name_txt = new javax.swing.JTextField();
        newsletter_checkbox = new java.awt.Checkbox();
        save_wishlist = new javax.swing.JButton();
        wishlist_info_txt = new javax.swing.JTextField();
        wishlist_price_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wishlist_table = new javax.swing.JTable();
        remove_from_wishlist = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        rantevou = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        test_drive_table2 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        testDrive = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        test_drive_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        test_drive_table1 = new javax.swing.JTable();
        selected_car_name = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        leitourgies_axrhsto = new javax.swing.JMenu();
        agora_btn = new javax.swing.JMenuItem();
        enoikiasi_btn = new javax.swing.JMenuItem();
        trade_in_btn = new javax.swing.JMenuItem();
        wishlist_btn = new javax.swing.JMenuItem();
        my_apps_btn = new javax.swing.JMenuItem();
        test_drive = new javax.swing.JMenuItem();
        edit_profile_button = new javax.swing.JMenu();
        Logout_button = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarDeal by P.B. C. D. A. G. & G. L.");
        setPreferredSize(new java.awt.Dimension(1417, 643));
        setResizable(false);

        parent_panel.setLayout(new java.awt.CardLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardeal/logo_200x200.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("CarDeal - Client");

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addComponent(jLabel17))
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(539, 539, 539)
                        .addComponent(jLabel1)))
                .addContainerGap(548, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        parent_panel.add(Welcome, "card2");

        epexergasia_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        epexergasia_profile.setEnabled(false);
        epexergasia_profile.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                epexergasia_profileComponentAdded(evt);
            }
        });

        onoma_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoma_txtActionPerformed(evt);
            }
        });

        dief8insi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dief8insi_txtActionPerformed(evt);
            }
        });

        jLabel3.setText("Όνομα");

        jLabel4.setText("Επώνυμο");

        jLabel5.setText("Email");

        Update_DB.setText("Αποθήκευση");
        Update_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_DBActionPerformed(evt);
            }
        });

        jLabel6.setText("Διεύθυνση");

        jLabel7.setText("Αριθμός");

        jLabel8.setText("Τηλέφωνο");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Επεξεργασία Προφίλ");

        javax.swing.GroupLayout epexergasia_profileLayout = new javax.swing.GroupLayout(epexergasia_profile);
        epexergasia_profile.setLayout(epexergasia_profileLayout);
        epexergasia_profileLayout.setHorizontalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(email_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)))
                .addGap(39, 39, 39)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(telephone_txt)
                    .addComponent(dief8insi_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(jLabel9))
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(Update_DB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        epexergasia_profileLayout.setVerticalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addGap(91, 91, 91)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dief8insi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(26, 26, 26)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(telephone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Update_DB)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        parent_panel.add(epexergasia_profile, "card2");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("Shop");

        jButton5.setText("Προσθήκη στα αγαπημένα");

        wishlist_info_txt1.setEditable(false);
        wishlist_info_txt1.setEnabled(false);

        wishlist_price_txt1.setEditable(false);
        wishlist_price_txt1.setEnabled(false);

        jLabel21.setText("Όνομα");

        jLabel22.setText("Πληροφορίες");

        jLabel23.setText("Τιμή");

        wishlist_info_txt2.setEditable(false);
        wishlist_info_txt2.setEnabled(false);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("eikona");
        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel26.setText("Αναζήτηση:");

        jButton4.setText("οκ");

        jButton3.setText("Αγορά");

        wishlist_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(wishlist_table1);

        javax.swing.GroupLayout shopLayout = new javax.swing.GroupLayout(shop);
        shop.setLayout(shopLayout);
        shopLayout.setHorizontalGroup(
            shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(shopLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(shopLayout.createSequentialGroup()
                        .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(114, 114, 114)
                        .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(shopLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(25, 25, 25)
                                .addComponent(wishlist_info_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(shopLayout.createSequentialGroup()
                                .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22))
                                .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(shopLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(wishlist_price_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shopLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wishlist_info_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shopLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButton3)))))
                .addGap(116, 116, 116))
        );
        shopLayout.setVerticalGroup(
            shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shopLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel20)
                .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shopLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(wishlist_info_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(wishlist_info_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wishlist_price_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(143, 143, 143)
                        .addComponent(jButton3))
                    .addGroup(shopLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(shopLayout.createSequentialGroup()
                                .addGroup(shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(shopLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        parent_panel.add(shop, "card4");

        javax.swing.GroupLayout rentLayout = new javax.swing.GroupLayout(rent);
        rent.setLayout(rentLayout);
        rentLayout.setHorizontalGroup(
            rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        rentLayout.setVerticalGroup(
            rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        parent_panel.add(rent, "card5");

        javax.swing.GroupLayout trade_inLayout = new javax.swing.GroupLayout(trade_in);
        trade_in.setLayout(trade_inLayout);
        trade_inLayout.setHorizontalGroup(
            trade_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        trade_inLayout.setVerticalGroup(
            trade_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        parent_panel.add(trade_in, "card6");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Wishlist");

        wishlist_name_txt.setEditable(false);
        wishlist_name_txt.setEnabled(false);

        newsletter_checkbox.setLabel("Αποστολή μηνυμάτων για το συγκεκριμένο προϊόν");

        save_wishlist.setText("Αποθήκευση");
        save_wishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_wishlistActionPerformed(evt);
            }
        });

        wishlist_info_txt.setEditable(false);
        wishlist_info_txt.setEnabled(false);

        wishlist_price_txt.setEditable(false);
        wishlist_price_txt.setEnabled(false);

        jLabel16.setText("Όνομα");

        jLabel18.setText("Πληροφορίες");

        jLabel19.setText("Τιμή");

        wishlist_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(wishlist_table);

        remove_from_wishlist.setText("Αφαίρεση από τα αγαπημένα");
        remove_from_wishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_from_wishlistActionPerformed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("eikona");
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout wishlistLayout = new javax.swing.GroupLayout(wishlist);
        wishlist.setLayout(wishlistLayout);
        wishlistLayout.setHorizontalGroup(
            wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishlistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(596, 596, 596))
            .addGroup(wishlistLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wishlistLayout.createSequentialGroup()
                        .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(wishlistLayout.createSequentialGroup()
                                .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16))
                                .addGap(25, 25, 25)
                                .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wishlist_info_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wishlist_price_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wishlist_name_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wishlistLayout.createSequentialGroup()
                        .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(wishlistLayout.createSequentialGroup()
                                .addComponent(remove_from_wishlist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(save_wishlist))
                            .addComponent(newsletter_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))))
        );
        wishlistLayout.setVerticalGroup(
            wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishlistLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wishlistLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wishlist_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wishlist_info_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wishlist_price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(newsletter_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(wishlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_wishlist)
                            .addComponent(remove_from_wishlist))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wishlistLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        parent_panel.add(wishlist, "card7");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Ραντεβού για ανταλλαγή οχήματος");

        test_drive_table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ημερομηνία", "Ώρα", "Όχημα"
            }
        ));
        jScrollPane5.setViewportView(test_drive_table2);

        jLabel28.setText("Κατάσταση");

        jLabel29.setText("Τιμή");

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rantevouLayout = new javax.swing.GroupLayout(rantevou);
        rantevou.setLayout(rantevouLayout);
        rantevouLayout.setHorizontalGroup(
            rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rantevouLayout.createSequentialGroup()
                .addGroup(rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rantevouLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addGroup(rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(rantevouLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addGap(500, 500, 500))
        );
        rantevouLayout.setVerticalGroup(
            rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rantevouLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel15)
                .addGroup(rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rantevouLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(rantevouLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(rantevouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        parent_panel.add(rantevou, "card8");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Test drive");

        jButton1.setText("Επιβεβαίωση στοιχείων");

        jButton2.setText("Επιβεβαίωση κράτησης");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Επιλογή ημερομηνίας");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("eikona");

        jLabel14.setText("Διαθέσιμα οχήματα");

        test_drive_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ημερομηνία", "Ώρα"
            }
        ));
        jScrollPane1.setViewportView(test_drive_table);

        test_drive_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Μάρκα", "Μοντέλο", "Χρονολογία"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(test_drive_table1);

        selected_car_name.setEditable(false);
        selected_car_name.setEnabled(false);

        javax.swing.GroupLayout testDriveLayout = new javax.swing.GroupLayout(testDrive);
        testDrive.setLayout(testDriveLayout);
        testDriveLayout.setHorizontalGroup(
            testDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testDriveLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(99, 99, 99))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testDriveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(testDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selected_car_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testDriveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(628, 628, 628))
        );
        testDriveLayout.setVerticalGroup(
            testDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testDriveLayout.createSequentialGroup()
                .addGroup(testDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(testDriveLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selected_car_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(25, 25, 25))
                    .addGroup(testDriveLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(testDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(testDriveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );

        parent_panel.add(testDrive, "card9");

        leitourgies_axrhsto.setText("Λειτουργίες");
        leitourgies_axrhsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leitourgies_axrhstoActionPerformed(evt);
            }
        });

        agora_btn.setText("Οχήματα προς αγορά");
        agora_btn.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                agora_btnMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        agora_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agora_btnMouseClicked(evt);
            }
        });
        agora_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agora_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(agora_btn);

        enoikiasi_btn.setText("Οχήματα προς ενοικίαση");
        enoikiasi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enoikiasi_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(enoikiasi_btn);

        trade_in_btn.setText("Ραντεβού για Trade In");
        trade_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trade_in_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(trade_in_btn);

        wishlist_btn.setText("Wishlist");
        wishlist_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishlist_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(wishlist_btn);

        my_apps_btn.setText("Τα ραντεβού μου");
        my_apps_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                my_apps_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(my_apps_btn);

        test_drive.setText("Test drive");
        test_drive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_driveActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(test_drive);

        jMenuBar1.add(leitourgies_axrhsto);

        edit_profile_button.setText("Επεξεργασία προφιλ");
        edit_profile_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                edit_profile_buttonMenuSelected(evt);
            }
        });
        edit_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(edit_profile_button);

        Logout_button.setText("Αποσύνδεση");
        Logout_button.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                Logout_buttonMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        Logout_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Logout_buttonMenuSelected(evt);
            }
        });
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(Logout_button);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void close() { 
    this.setVisible(false); // FUNCTION GIA KLEISIMO PARA8IROU
    this.dispose();
}
  private void loadUserProfile() {
    String username = Session.getUsername();
    try {
        String sql = "SELECT FirstName, LastName, Email, Telephone, Street, StreetNum FROM User WHERE Username = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            onoma_txt.setText(rs.getString("FirstName"));
            eponimo_txt.setText(rs.getString("LastName"));
            email_txt.setText(rs.getString("Email"));
            dief8insi_txt.setText(rs.getString("Street"));
            ari8mos_txt.setText(rs.getString("StreetNum"));
            telephone_txt.setText(rs.getString("Telephone"));
        }
        rs.close();
        pst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
}
    private void agora_btnMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_agora_btnMenuKeyPressed

    }//GEN-LAST:event_agora_btnMenuKeyPressed

    private void agora_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agora_btnMouseClicked

    }//GEN-LAST:event_agora_btnMouseClicked

    private void agora_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agora_btnActionPerformed
        parent_panel.removeAll();
        parent_panel.add(shop);
        parent_panel.repaint();
        parent_panel.revalidate();  
    }//GEN-LAST:event_agora_btnActionPerformed

    private void enoikiasi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enoikiasi_btnActionPerformed
        parent_panel.removeAll();
        parent_panel.add(rent);
        parent_panel.repaint();
        parent_panel.revalidate();      
    }//GEN-LAST:event_enoikiasi_btnActionPerformed

    private void trade_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trade_in_btnActionPerformed
        parent_panel.removeAll();
        parent_panel.add(trade_in);
        parent_panel.repaint();
        parent_panel.revalidate();     
    }//GEN-LAST:event_trade_in_btnActionPerformed

    private void leitourgies_axrhstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leitourgies_axrhstoActionPerformed

    }//GEN-LAST:event_leitourgies_axrhstoActionPerformed

    private void edit_profile_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_edit_profile_buttonMenuSelected
        parent_panel.removeAll();
        parent_panel.add(epexergasia_profile);
        parent_panel.repaint();
        parent_panel.revalidate();
        String username = Session.getUsername();
        loadUserProfile();

    }//GEN-LAST:event_edit_profile_buttonMenuSelected

    private void edit_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile_buttonActionPerformed

    private void Logout_buttonMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_Logout_buttonMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_buttonMenuKeyPressed

    private void Logout_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Logout_buttonMenuSelected
        Login Lg = new Login();
        Lg.setVisible(true);
        Lg.pack();
        Lg.setLocationRelativeTo(null);
        Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
        close();
    }//GEN-LAST:event_Logout_buttonMenuSelected

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        Login Lg = new Login();
        Lg.setVisible(true);
        Lg.pack();
        Lg.setLocationRelativeTo(null);
        Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
        close(); // axristooooo
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void onoma_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoma_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onoma_txtActionPerformed

    private void dief8insi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dief8insi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dief8insi_txtActionPerformed

    private void Update_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_DBActionPerformed
    String username = Session.getUsername();                           
        try{
            String value1= onoma_txt.getText();
            String value2= eponimo_txt.getText();
            String value3= email_txt.getText();
            String value4= dief8insi_txt.getText();
            String value5= ari8mos_txt.getText();
            String value6= telephone_txt.getText();
            String sql ="UPDATE  User set FirstName = ?, LastName=?, email=?, Telephone=?, Street=?, StreetNum=? WHERE Username=? ";
            pst=conn.prepareStatement(sql);
            pst.setString(1, value1);
            pst.setString(2, value2);
            pst.setString(3, value3);
            pst.setString(4, value6);
            pst.setString(5, value4);
            pst.setString(6, value5);
            pst.setString(7, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data updated succesfully");
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);}
       
    }//GEN-LAST:event_Update_DBActionPerformed

    private void epexergasia_profileComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_epexergasia_profileComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_epexergasia_profileComponentAdded

    private void wishlist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishlist_btnActionPerformed
        parent_panel.removeAll();
        parent_panel.add(wishlist);
        parent_panel.repaint();
        parent_panel.revalidate();  
    }//GEN-LAST:event_wishlist_btnActionPerformed

    private void my_apps_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_my_apps_btnActionPerformed
        parent_panel.removeAll();
        parent_panel.add(rantevou);
        parent_panel.repaint();
        parent_panel.revalidate();  
    }//GEN-LAST:event_my_apps_btnActionPerformed

    private void test_driveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_driveActionPerformed
        parent_panel.removeAll();
        parent_panel.add(testDrive);
        parent_panel.repaint();
        parent_panel.revalidate();
    }//GEN-LAST:event_test_driveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void remove_from_wishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_from_wishlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remove_from_wishlistActionPerformed

    private void save_wishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_wishlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_wishlistActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout_button;
    private javax.swing.JButton Update_DB;
    private javax.swing.JPanel Welcome;
    private javax.swing.JMenuItem agora_btn;
    private javax.swing.JTextField ari8mos_txt;
    private javax.swing.JTextField dief8insi_txt;
    private javax.swing.JMenu edit_profile_button;
    private javax.swing.JTextField email_txt;
    private javax.swing.JMenuItem enoikiasi_btn;
    private javax.swing.JPanel epexergasia_profile;
    private javax.swing.JTextField eponimo_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenu leitourgies_axrhsto;
    private javax.swing.JMenuItem my_apps_btn;
    private java.awt.Checkbox newsletter_checkbox;
    private javax.swing.JTextField onoma_txt;
    private javax.swing.JPanel parent_panel;
    private javax.swing.JPanel rantevou;
    private javax.swing.JButton remove_from_wishlist;
    private javax.swing.JPanel rent;
    private javax.swing.JButton save_wishlist;
    private javax.swing.JTextField selected_car_name;
    private javax.swing.JPanel shop;
    private javax.swing.JTextField telephone_txt;
    private javax.swing.JPanel testDrive;
    private javax.swing.JMenuItem test_drive;
    private javax.swing.JTable test_drive_table;
    private javax.swing.JTable test_drive_table1;
    private javax.swing.JTable test_drive_table2;
    private javax.swing.JPanel trade_in;
    private javax.swing.JMenuItem trade_in_btn;
    private javax.swing.JPanel wishlist;
    private javax.swing.JMenuItem wishlist_btn;
    private javax.swing.JTextField wishlist_info_txt;
    private javax.swing.JTextField wishlist_info_txt1;
    private javax.swing.JTextField wishlist_info_txt2;
    private javax.swing.JTextField wishlist_name_txt;
    private javax.swing.JTextField wishlist_price_txt;
    private javax.swing.JTextField wishlist_price_txt1;
    private javax.swing.JTable wishlist_table;
    private javax.swing.JTable wishlist_table1;
    // End of variables declaration//GEN-END:variables
}
