/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardeal;
import java.sql.*;
import javax.swing.*;

public class customer extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs =null;
PreparedStatement pst=null;
    /**
     * Creates new form customer
     */
    public customer() {
         initComponents();
        conn = connect.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent_panel = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        epexergasia_profile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onoma_txt = new javax.swing.JTextField();
        eponimo_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        dief8insi_txt = new javax.swing.JTextField();
        ari8mos_txt = new javax.swing.JTextField();
        telephone_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Update_DB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        leitourgies_axrhsto = new javax.swing.JMenu();
        agora_btn = new javax.swing.JMenuItem();
        enoikiasi_btn = new javax.swing.JMenuItem();
        trade_in_btn = new javax.swing.JMenuItem();
        wishlist_btn = new javax.swing.JMenuItem();
        my_apps_btn = new javax.swing.JMenuItem();
        edit_profile_button = new javax.swing.JMenu();
        Logout_button = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarDeal by P.B. C. D. A. G. & G. L.");
        setPreferredSize(new java.awt.Dimension(1417, 643));

        parent_panel.setLayout(new java.awt.CardLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardeal/logo_200x200.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("CarDeal - Client");

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addComponent(jLabel17))
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(539, 539, 539)
                        .addComponent(jLabel1)))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        parent_panel.add(Welcome, "card2");

        epexergasia_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        epexergasia_profile.setEnabled(false);
        epexergasia_profile.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                epexergasia_profileComponentAdded(evt);
            }
        });

        onoma_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoma_txtActionPerformed(evt);
            }
        });

        dief8insi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dief8insi_txtActionPerformed(evt);
            }
        });

        jLabel3.setText("Όνομα");

        jLabel4.setText("Επώνυμο");

        jLabel5.setText("Email");

        Update_DB.setText("Αποθήκευση");
        Update_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_DBActionPerformed(evt);
            }
        });

        jLabel6.setText("Διεύθυνση");

        jLabel7.setText("Αριθμός");

        jLabel8.setText("Τηλέφωνο");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Επεξεργασία Προφίλ");

        javax.swing.GroupLayout epexergasia_profileLayout = new javax.swing.GroupLayout(epexergasia_profile);
        epexergasia_profile.setLayout(epexergasia_profileLayout);
        epexergasia_profileLayout.setHorizontalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(email_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)))
                .addGap(39, 39, 39)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(telephone_txt)
                    .addComponent(dief8insi_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(jLabel9))
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(Update_DB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        epexergasia_profileLayout.setVerticalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addGap(91, 91, 91)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dief8insi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(26, 26, 26)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(telephone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(Update_DB)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        parent_panel.add(epexergasia_profile, "card2");

        leitourgies_axrhsto.setText("Λειτουργίες");
        leitourgies_axrhsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leitourgies_axrhstoActionPerformed(evt);
            }
        });

        agora_btn.setText("Οχήματα προς αγορά");
        agora_btn.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                agora_btnMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        agora_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agora_btnMouseClicked(evt);
            }
        });
        agora_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agora_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(agora_btn);

        enoikiasi_btn.setText("Οχήματα προς ενοικίαση");
        enoikiasi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enoikiasi_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(enoikiasi_btn);

        trade_in_btn.setText("Ραντεβού για Trade In");
        trade_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trade_in_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(trade_in_btn);

        wishlist_btn.setText("Wishlist");
        wishlist_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishlist_btnActionPerformed(evt);
            }
        });
        leitourgies_axrhsto.add(wishlist_btn);

        my_apps_btn.setText("Τα ραντεβού μου");
        leitourgies_axrhsto.add(my_apps_btn);

        jMenuBar1.add(leitourgies_axrhsto);

        edit_profile_button.setText("Επεξεργασία προφιλ");
        edit_profile_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                edit_profile_buttonMenuSelected(evt);
            }
        });
        edit_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_profile_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(edit_profile_button);

        Logout_button.setText("Αποσύνδεση");
        Logout_button.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                Logout_buttonMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        Logout_button.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Logout_buttonMenuSelected(evt);
            }
        });
        Logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_buttonActionPerformed(evt);
            }
        });
        jMenuBar1.add(Logout_button);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void close() { 
    this.setVisible(false); // FUNCTION GIA KLEISIMO PARA8IROU
    this.dispose();
}
  private void loadUserProfile() {
    String username = Session.getUsername();
    try {
        String sql = "SELECT FirstName, LastName, Email, Telephone, Street, StreetNum FROM User WHERE Username = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            onoma_txt.setText(rs.getString("FirstName"));
            eponimo_txt.setText(rs.getString("LastName"));
            email_txt.setText(rs.getString("Email"));
            dief8insi_txt.setText(rs.getString("Street"));
            ari8mos_txt.setText(rs.getString("StreetNum"));
            telephone_txt.setText(rs.getString("Telephone"));
        }
        rs.close();
        pst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
}
    private void agora_btnMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_agora_btnMenuKeyPressed

    }//GEN-LAST:event_agora_btnMenuKeyPressed

    private void agora_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agora_btnMouseClicked

    }//GEN-LAST:event_agora_btnMouseClicked

    private void agora_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agora_btnActionPerformed
      
    }//GEN-LAST:event_agora_btnActionPerformed

    private void enoikiasi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enoikiasi_btnActionPerformed
    
    }//GEN-LAST:event_enoikiasi_btnActionPerformed

    private void trade_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trade_in_btnActionPerformed
   
    }//GEN-LAST:event_trade_in_btnActionPerformed

    private void leitourgies_axrhstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leitourgies_axrhstoActionPerformed

    }//GEN-LAST:event_leitourgies_axrhstoActionPerformed

    private void edit_profile_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_edit_profile_buttonMenuSelected
        parent_panel.removeAll();
        parent_panel.add(epexergasia_profile);
        parent_panel.repaint();
        parent_panel.revalidate();
        String username = Session.getUsername();
        loadUserProfile();

    }//GEN-LAST:event_edit_profile_buttonMenuSelected

    private void edit_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_profile_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_profile_buttonActionPerformed

    private void Logout_buttonMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_Logout_buttonMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout_buttonMenuKeyPressed

    private void Logout_buttonMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Logout_buttonMenuSelected
        Login Lg = new Login();
        Lg.setVisible(true);
        Lg.pack();
        Lg.setLocationRelativeTo(null);
        Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
        close();
    }//GEN-LAST:event_Logout_buttonMenuSelected

    private void Logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_buttonActionPerformed
        Login Lg = new Login();
        Lg.setVisible(true);
        Lg.pack();
        Lg.setLocationRelativeTo(null);
        Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
        close(); // axristooooo
    }//GEN-LAST:event_Logout_buttonActionPerformed

    private void onoma_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoma_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onoma_txtActionPerformed

    private void dief8insi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dief8insi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dief8insi_txtActionPerformed

    private void Update_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_DBActionPerformed
    String username = Session.getUsername();                           
        try{
            String value1= onoma_txt.getText();
            String value2= eponimo_txt.getText();
            String value3= email_txt.getText();
            String value4= dief8insi_txt.getText();
            String value5= ari8mos_txt.getText();
            String value6= telephone_txt.getText();
            String sql ="UPDATE  User set FirstName = ?, LastName=?, email=?, Telephone=?, Street=?, StreetNum=? WHERE Username=? ";
            pst=conn.prepareStatement(sql);
            pst.setString(1, value1);
            pst.setString(2, value2);
            pst.setString(3, value3);
            pst.setString(4, value6);
            pst.setString(5, value4);
            pst.setString(6, value5);
            pst.setString(7, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data updated succesfully");
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);}
       
    }//GEN-LAST:event_Update_DBActionPerformed

    private void epexergasia_profileComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_epexergasia_profileComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_epexergasia_profileComponentAdded

    private void wishlist_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishlist_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wishlist_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout_button;
    private javax.swing.JButton Update_DB;
    private javax.swing.JPanel Welcome;
    private javax.swing.JMenuItem agora_btn;
    private javax.swing.JTextField ari8mos_txt;
    private javax.swing.JTextField dief8insi_txt;
    private javax.swing.JMenu edit_profile_button;
    private javax.swing.JTextField email_txt;
    private javax.swing.JMenuItem enoikiasi_btn;
    private javax.swing.JPanel epexergasia_profile;
    private javax.swing.JTextField eponimo_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu leitourgies_axrhsto;
    private javax.swing.JMenuItem my_apps_btn;
    private javax.swing.JTextField onoma_txt;
    private javax.swing.JPanel parent_panel;
    private javax.swing.JTextField telephone_txt;
    private javax.swing.JMenuItem trade_in_btn;
    private javax.swing.JMenuItem wishlist_btn;
    // End of variables declaration//GEN-END:variables
}
