/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardeal;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class service extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form service
     */
    public service() {
        initComponents();
        conn = connect.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        service_dash = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        service_notes_txt = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mileage_txt = new javax.swing.JTextField();
        carplate_txt = new javax.swing.JTextField();
        model_txt = new javax.swing.JTextField();
        year_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ipovoli_btn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        pelatis_txt = new javax.swing.JTextField();
        new_customer_btn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        service_table = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        servicehistory_table = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        pros8ikiadalaktikwn_btn = new javax.swing.JButton();
        messages = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        send_new_message_btn = new javax.swing.JButton();
        new_message_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_show = new javax.swing.JTable();
        epexergasia_profile = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onoma_txt = new javax.swing.JTextField();
        eponimo_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        dief8insi_txt = new javax.swing.JTextField();
        ari8mos_txt = new javax.swing.JTextField();
        telephone_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        save_data = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        trade_in_dash = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        year_txt1 = new javax.swing.JTextField();
        deny_btn1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pelatis_txt1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        make_txt1 = new javax.swing.JTextField();
        price_txt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tradein_table = new javax.swing.JTable();
        accepttrdin_btn = new javax.swing.JButton();
        new_client_dash = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        email_new_txt1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        dief8insi_txt1 = new javax.swing.JTextField();
        ari8mos_txt1 = new javax.swing.JTextField();
        telephone_txt1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Update_DB1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        onoma_txt1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        eponimo_txt1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        new_vin_txt = new javax.swing.JTextField();
        new_make_txt = new javax.swing.JTextField();
        new_year_txt = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        new_model_txt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        leitourgies_btn = new javax.swing.JMenu();
        trade_in_btn = new javax.swing.JMenuItem();
        minimata_btn = new javax.swing.JMenuItem();
        service_btn = new javax.swing.JMenuItem();
        edit_profile_btn = new javax.swing.JMenu();
        Logout_btn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CarDeal by P.B. C. D. A. G. & G. L.");

        parentPanel.setPreferredSize(new java.awt.Dimension(1417, 620));
        parentPanel.setLayout(new java.awt.CardLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardeal/logo_200x200.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("CarDeal - Service");

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel1))
                    .addGroup(WelcomeLayout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addComponent(jLabel17)))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        parentPanel.add(Welcome, "card2");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Service");

        service_notes_txt.setColumns(20);
        service_notes_txt.setRows(5);
        jScrollPane1.setViewportView(service_notes_txt);

        jLabel11.setText("Χιλιόμετρα");

        jLabel12.setText("Πινακίδα");

        jLabel13.setText("Μοντέλο");

        jLabel15.setText("Χρονολογία");

        mileage_txt.setFocusable(false);
        mileage_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mileage_txtActionPerformed(evt);
            }
        });

        carplate_txt.setFocusable(false);

        model_txt.setFocusable(false);

        year_txt.setFocusable(false);

        jLabel16.setText("Σημειώσεις Service");

        ipovoli_btn.setText("Υποβολή Service");
        ipovoli_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipovoli_btnActionPerformed(evt);
            }
        });

        jLabel18.setText("Πελάτης");

        pelatis_txt.setFocusable(false);
        pelatis_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelatis_txtActionPerformed(evt);
            }
        });

        new_customer_btn.setText("Νέος Πελάτης");
        new_customer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_customer_btnActionPerformed(evt);
            }
        });

        jLabel20.setText("Στοιχεία οχήματος");

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        service_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        service_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                service_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(service_table);

        servicehistory_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(servicehistory_table);

        jLabel19.setText("Ιστορικό Service");

        pros8ikiadalaktikwn_btn.setText("Προσθήκη Ανταλλακτικών");

        javax.swing.GroupLayout service_dashLayout = new javax.swing.GroupLayout(service_dash);
        service_dash.setLayout(service_dashLayout);
        service_dashLayout.setHorizontalGroup(
            service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(service_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(service_dashLayout.createSequentialGroup()
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(service_dashLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(61, 61, 61))
                                    .addGroup(service_dashLayout.createSequentialGroup()
                                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel18))
                                        .addGap(65, 65, 65)
                                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(mileage_txt)
                                            .addComponent(carplate_txt)
                                            .addComponent(model_txt)
                                            .addComponent(year_txt)
                                            .addComponent(pelatis_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10)))
                            .addGroup(service_dashLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(pros8ikiadalaktikwn_btn)))
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ipovoli_btn)
                                .addGap(95, 95, 95))
                            .addGroup(service_dashLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                                .addComponent(new_customer_btn)
                                .addGap(285, 285, 285))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(317, 317, 317))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(153, 153, 153))
        );
        service_dashLayout.setVerticalGroup(
            service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, service_dashLayout.createSequentialGroup()
                .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(service_dashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mileage_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(carplate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(year_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(pelatis_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(service_dashLayout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(service_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipovoli_btn)
                    .addComponent(pros8ikiadalaktikwn_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(new_customer_btn)
                .addGap(17, 17, 17))
            .addGroup(service_dashLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        parentPanel.add(service_dash, "card4");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Μηνύματα");

        send_new_message_btn.setText("Αποστολή");
        send_new_message_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_new_message_btnActionPerformed(evt);
            }
        });

        new_message_txt.setText("Πληκτρολογήστε νέο μήνυμα");
        new_message_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_message_txtActionPerformed(evt);
            }
        });

        Table_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Table_show);

        javax.swing.GroupLayout messagesLayout = new javax.swing.GroupLayout(messages);
        messages.setLayout(messagesLayout);
        messagesLayout.setHorizontalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagesLayout.createSequentialGroup()
                .addGroup(messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagesLayout.createSequentialGroup()
                        .addContainerGap(662, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane2))
                .addGroup(messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messagesLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(send_new_message_btn))
                    .addGroup(messagesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(new_message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        messagesLayout.setVerticalGroup(
            messagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(send_new_message_btn)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );

        parentPanel.add(messages, "card5");

        epexergasia_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        epexergasia_profile.setEnabled(false);
        epexergasia_profile.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                epexergasia_profileComponentAdded(evt);
            }
        });

        onoma_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoma_txtActionPerformed(evt);
            }
        });

        dief8insi_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dief8insi_txtActionPerformed(evt);
            }
        });

        jLabel3.setText("Όνομα");

        jLabel4.setText("Επώνυμο");

        jLabel5.setText("Email");

        save_data.setText("Αποθήκευση");
        save_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_dataActionPerformed(evt);
            }
        });

        jLabel6.setText("Διεύθυνση");

        jLabel7.setText("Αριθμός");

        jLabel8.setText("Τηλέφωνο");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Επεξεργασία Προφίλ");

        javax.swing.GroupLayout epexergasia_profileLayout = new javax.swing.GroupLayout(epexergasia_profile);
        epexergasia_profile.setLayout(epexergasia_profileLayout);
        epexergasia_profileLayout.setHorizontalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(email_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)))
                .addGap(39, 39, 39)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(telephone_txt)
                    .addComponent(dief8insi_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(555, 555, 555)
                        .addComponent(jLabel9))
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(save_data)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        epexergasia_profileLayout.setVerticalGroup(
            epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(epexergasia_profileLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addGap(91, 91, 91)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(epexergasia_profileLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onoma_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dief8insi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ari8mos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eponimo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(26, 26, 26)
                .addGroup(epexergasia_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(telephone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(save_data)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        parentPanel.add(epexergasia_profile, "card2");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Στοιχεία οχήματος");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("Trade-In");

        deny_btn1.setText("Απόριψη Trade In");
        deny_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deny_btn1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Αυτοκίνητο");

        jLabel26.setText("Πελάτης");

        pelatis_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelatis_txt1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Χρονολογία");

        make_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_txt1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Ποσό αγοράς");

        tradein_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tradein_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tradein_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tradein_table);

        accepttrdin_btn.setText("Αποδοχή Trade In");
        accepttrdin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepttrdin_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trade_in_dashLayout = new javax.swing.GroupLayout(trade_in_dash);
        trade_in_dash.setLayout(trade_in_dashLayout);
        trade_in_dashLayout.setHorizontalGroup(
            trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trade_in_dashLayout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trade_in_dashLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addGap(207, 207, 207)
                .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(trade_in_dashLayout.createSequentialGroup()
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30))
                        .addGap(57, 57, 57)
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(year_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pelatis_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(make_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(trade_in_dashLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(80, 80, 80))
                    .addGroup(trade_in_dashLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(accepttrdin_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deny_btn1)))
                .addGap(228, 228, 228))
        );
        trade_in_dashLayout.setVerticalGroup(
            trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trade_in_dashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(22, 22, 22)
                .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trade_in_dashLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel21)
                        .addGap(58, 58, 58)
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(make_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pelatis_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(77, 77, 77)
                        .addGroup(trade_in_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deny_btn1)
                            .addComponent(accepttrdin_btn))
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)))
        );

        parentPanel.add(trade_in_dash, "card6");

        jLabel23.setText("Τηλέφωνο");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel31.setText("Νέος Πελάτης");

        dief8insi_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dief8insi_txt1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Όνομα");

        jLabel33.setText("Επώνυμο");

        jLabel34.setText("Email");

        Update_DB1.setText("Αποθήκευση");
        Update_DB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_DB1ActionPerformed(evt);
            }
        });

        jLabel35.setText("Διεύθυνση");

        onoma_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoma_txt1ActionPerformed(evt);
            }
        });

        jLabel36.setText("Αριθμός");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setText("Στοιχεία Πελάτη");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setText("Στοιχεία οχήματος");

        jLabel39.setText("VIN");

        jLabel40.setText("Μάρκα");

        jLabel41.setText("Έτος");

        jLabel42.setText("Μοντέλο");

        javax.swing.GroupLayout new_client_dashLayout = new javax.swing.GroupLayout(new_client_dash);
        new_client_dash.setLayout(new_client_dashLayout);
        new_client_dashLayout.setHorizontalGroup(
            new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_client_dashLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(239, 239, 239))
            .addGroup(new_client_dashLayout.createSequentialGroup()
                .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_client_dashLayout.createSequentialGroup()
                        .addGap(631, 631, 631)
                        .addComponent(jLabel31))
                    .addGroup(new_client_dashLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(onoma_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(eponimo_txt1)
                            .addComponent(email_new_txt1))
                        .addGap(82, 82, 82)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35))
                        .addGap(39, 39, 39)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ari8mos_txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(dief8insi_txt1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephone_txt1))
                        .addGap(83, 83, 83)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addGap(25, 25, 25)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(new_vin_txt)
                            .addComponent(new_make_txt)
                            .addComponent(new_year_txt)
                            .addComponent(new_model_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addGroup(new_client_dashLayout.createSequentialGroup()
                        .addGap(619, 619, 619)
                        .addComponent(Update_DB1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        new_client_dashLayout.setVerticalGroup(
            new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_client_dashLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel31)
                .addGap(33, 33, 33)
                .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(39, 39, 39)
                .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_client_dashLayout.createSequentialGroup()
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onoma_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eponimo_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(26, 26, 26)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_new_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)))
                    .addGroup(new_client_dashLayout.createSequentialGroup()
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dief8insi_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel39)
                            .addComponent(new_vin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ari8mos_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)
                                .addComponent(new_make_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel36))
                        .addGap(26, 26, 26)
                        .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(telephone_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(new_model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(new_client_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(new_year_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(Update_DB1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        parentPanel.add(new_client_dash, "card7");

        leitourgies_btn.setText("Λειτουργίες");

        trade_in_btn.setText("Οχήματα προς ανταλλαγή");
        trade_in_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trade_in_btnActionPerformed(evt);
            }
        });
        leitourgies_btn.add(trade_in_btn);

        minimata_btn.setText("Μηνύματα");
        minimata_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimata_btnActionPerformed(evt);
            }
        });
        leitourgies_btn.add(minimata_btn);

        service_btn.setText("Οχήματα για service");
        service_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service_btnActionPerformed(evt);
            }
        });
        leitourgies_btn.add(service_btn);

        jMenuBar1.add(leitourgies_btn);

        edit_profile_btn.setText("Επεξεργασία προφίλ");
        edit_profile_btn.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                edit_profile_btnMenuSelected(evt);
            }
        });
        jMenuBar1.add(edit_profile_btn);

        Logout_btn.setText("Αποσύνδεση");
        Logout_btn.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Logout_btnMenuSelected(evt);
            }
        });
        Logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btnActionPerformed(evt);
            }
        });
        jMenuBar1.add(Logout_btn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void close() {
        this.setVisible(false); // FUNCTION GIA KLEISIMO PARA8IROU
        this.dispose();
    }

    private void loadUserProfile() {
        String username = Session.getUsername();
        try {
            String sql = "SELECT FirstName, LastName, Email, Street, StreetNum, Telephone FROM User WHERE Username = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                onoma_txt.setText(rs.getString("FirstName"));
                eponimo_txt.setText(rs.getString("LastName"));
                email_txt.setText(rs.getString("Email"));
                dief8insi_txt.setText(rs.getString("Street"));
                ari8mos_txt.setText(rs.getString("StreetNum"));
                telephone_txt.setText(rs.getString("Telephone"));
            }
            rs.close();
            pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
        
       
    }

    private void Update_Table(String tablename, JTable table_show) {

        try {
            String sql = "SELECT * FROM " + tablename;
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_show.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    private void trade_in_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trade_in_btnActionPerformed
        parentPanel.removeAll();
        parentPanel.add(trade_in_dash);
        parentPanel.repaint();
        parentPanel.revalidate();
        try {
            String sql = "SELECT * FROM Trade_In Where TradeStatus = 'Pending' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tradein_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_trade_in_btnActionPerformed

    private void Logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btnActionPerformed

    }//GEN-LAST:event_Logout_btnActionPerformed

    private void Logout_btnMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Logout_btnMenuSelected
        Login Lg = new Login();
        Lg.setVisible(true);
        Lg.pack();
        Lg.setLocationRelativeTo(null);
        Lg.setDefaultCloseOperation(apothiki.DISPOSE_ON_CLOSE);
        close();
    }//GEN-LAST:event_Logout_btnMenuSelected

    private void onoma_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoma_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onoma_txtActionPerformed

    private void dief8insi_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dief8insi_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dief8insi_txtActionPerformed

    private void save_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_dataActionPerformed
        String username = Session.getUsername();
        try {
            String value1 = onoma_txt.getText();
            String value2 = eponimo_txt.getText();
            String value3 = email_txt.getText();
            String value4 = dief8insi_txt.getText();
            String value5 = ari8mos_txt.getText();
            String value6 = telephone_txt.getText();
            String sql = "UPDATE  User set FirstName = ?, LastName=?, email=?, Telephone=?, Street=?, StreetNum=? WHERE Username=? ";
            pst = conn.prepareStatement(sql);
            pst.setString(1, value1);
            pst.setString(2, value2);
            pst.setString(3, value3);
            pst.setString(4, value6);
            pst.setString(5, value4);
            pst.setString(6, value5);
            pst.setString(7, username);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data updated succesfully");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_save_dataActionPerformed

    private void epexergasia_profileComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_epexergasia_profileComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_epexergasia_profileComponentAdded

    private void new_message_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_message_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_message_txtActionPerformed

    private void minimata_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimata_btnActionPerformed
        parentPanel.removeAll();
        parentPanel.add(messages);
        parentPanel.repaint();
        parentPanel.revalidate();
        Update_Table("Messages", Table_show);
    }//GEN-LAST:event_minimata_btnActionPerformed

    private void edit_profile_btnMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_edit_profile_btnMenuSelected
        parentPanel.removeAll();
        parentPanel.add(epexergasia_profile);
        parentPanel.repaint();
        parentPanel.revalidate();
        loadUserProfile();
    }//GEN-LAST:event_edit_profile_btnMenuSelected

    private void service_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_btnActionPerformed
        parentPanel.removeAll();
        parentPanel.add(service_dash);
        parentPanel.repaint();
        parentPanel.revalidate();
        Update_Table("Repairs", service_table);
    }//GEN-LAST:event_service_btnActionPerformed

    private void mileage_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mileage_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mileage_txtActionPerformed

    private void pelatis_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelatis_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelatis_txtActionPerformed

    private void pelatis_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelatis_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelatis_txt1ActionPerformed

    private void make_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_make_txt1ActionPerformed

    private void dief8insi_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dief8insi_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dief8insi_txt1ActionPerformed

    private void Update_DB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_DB1ActionPerformed
        parentPanel.removeAll();
        parentPanel.add(service_dash);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_Update_DB1ActionPerformed

    private void onoma_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoma_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onoma_txt1ActionPerformed

    private void new_customer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_customer_btnActionPerformed
        parentPanel.removeAll();
        parentPanel.add(new_client_dash);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_new_customer_btnActionPerformed

    private void send_new_message_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_new_message_btnActionPerformed
        String username = Session.getUsername();
        try {
            String sql = "INSERT INTO Messages (MessageText, SenderName) VALUES (?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, new_message_txt.getText());
            pst.setString(2, username);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Message Sent Succesfully!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        Update_Table("Messages", Table_show);
    }//GEN-LAST:event_send_new_message_btnActionPerformed

    private void tradein_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradein_tableMouseClicked
        try {
            int row = tradein_table.getSelectedRow();
            String Table_click = (tradein_table.getModel().getValueAt(row, 0).toString());
            String sql = "select * from Trade_In where TradeID='" + Table_click + "' AND  TradeStatus = 'pending'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("CustomerName");
                pelatis_txt1.setText(add1);
                String add2 = rs.getString("CarName");
                make_txt1.setText(add2);
                String add3 = rs.getString("CarModel");
                year_txt1.setText(add3);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_tradein_tableMouseClicked

    private void accepttrdin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepttrdin_btnActionPerformed
        String price_str = price_txt.getText().trim();
        int price = Integer.parseInt(price_str);
        try {
            int row = tradein_table.getSelectedRow();
            String Table_click = (tradein_table.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE Trade_In set Price = ? , TradeStatus ='Approved' where TradeID='" + Table_click + "'";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, price);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Trade in accepted successfuly!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
        try {
            String sql = "SELECT * FROM Trade_In Where TradeStatus = 'Pending' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tradein_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_accepttrdin_btnActionPerformed

    private void deny_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deny_btn1ActionPerformed
        try {
            int row = tradein_table.getSelectedRow();
            String Table_click = (tradein_table.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE Trade_In set TradeStatus='Denied' where TradeID='" + Table_click + "'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Trade in denied successfuly!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        try {
            String sql = "SELECT * FROM Trade_In Where TradeStatus = 'Pending' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tradein_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_deny_btn1ActionPerformed

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void service_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_service_tableMouseClicked
        try {
            int row = service_table.getSelectedRow();
            String Table_click = (service_table.getModel().getValueAt(row, 0).toString());
            String sql = "select * from Repairs where CarPlate='" + Table_click + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("Mileage");
                mileage_txt.setText(add1);
                String add2 = rs.getString("CarName");
                model_txt.setText(add2);
                String add3 = rs.getString("Model");
                year_txt.setText(add3);
                String add4 = rs.getString("OwnerName");
                pelatis_txt.setText(add4);
                String add5 = rs.getString("CarPlate");
                carplate_txt.setText(add5);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        try {
            int row = service_table.getSelectedRow();
            String Table_click = (service_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT sh.* FROM ServiceHistory sh JOIN CarCustomer cc ON sh.CarCostumerID = cc.CarCustomerID WHERE cc.CarPlate = '" + Table_click + "' AND cc.CarPlate IN (SELECT CarPlate FROM Repairs) AND cc.CarPlate IN (SELECT CarPlate FROM CarCustomer)";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            servicehistory_table.setModel(DbUtils.resultSetToTableModel(rs));
             parentPanel.removeAll();
        parentPanel.add(service_dash);
        parentPanel.repaint();
        parentPanel.revalidate();
        Update_Table("Repairs", service_table);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
       
    }//GEN-LAST:event_service_tableMouseClicked

    private void ipovoli_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipovoli_btnActionPerformed
    
  try {
    int row = service_table.getSelectedRow();
    String Table_click = service_table.getModel().getValueAt(row, 0).toString();

    String sql = "INSERT INTO ServiceHistory (CarCostumerId, ServiceType, Description) VALUES ((SELECT CarCustomerID FROM CarCustomer WHERE CarPlate = ?), ?, ?)";

    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, Table_click); 
    pst.setString(2, "General Service"); 
    pst.setString(3, service_notes_txt.getText()); 

    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Service history added successfully.");
    pst.close();
    String del = "DELETE from Repairs where CarPlate='" + Table_click + "' ";
    PreparedStatement pst2 = conn.prepareStatement(del);
    pst2.execute();

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex);
}
  
    }//GEN-LAST:event_ipovoli_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Logout_btn;
    private javax.swing.JTable Table_show;
    private javax.swing.JButton Update_DB1;
    private javax.swing.JPanel Welcome;
    private javax.swing.JButton accepttrdin_btn;
    private javax.swing.JTextField ari8mos_txt;
    private javax.swing.JTextField ari8mos_txt1;
    private javax.swing.JTextField carplate_txt;
    private javax.swing.JButton deny_btn1;
    private javax.swing.JTextField dief8insi_txt;
    private javax.swing.JTextField dief8insi_txt1;
    private javax.swing.JMenu edit_profile_btn;
    private javax.swing.JTextField email_new_txt1;
    private javax.swing.JTextField email_txt;
    private javax.swing.JPanel epexergasia_profile;
    private javax.swing.JTextField eponimo_txt;
    private javax.swing.JTextField eponimo_txt1;
    private javax.swing.JButton ipovoli_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenu leitourgies_btn;
    private javax.swing.JTextField make_txt1;
    private javax.swing.JPanel messages;
    private javax.swing.JTextField mileage_txt;
    private javax.swing.JMenuItem minimata_btn;
    private javax.swing.JTextField model_txt;
    private javax.swing.JPanel new_client_dash;
    private javax.swing.JButton new_customer_btn;
    private javax.swing.JTextField new_make_txt;
    private javax.swing.JTextField new_message_txt;
    private javax.swing.JTextField new_model_txt;
    private javax.swing.JTextField new_vin_txt;
    private javax.swing.JTextField new_year_txt;
    private javax.swing.JTextField onoma_txt;
    private javax.swing.JTextField onoma_txt1;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTextField pelatis_txt;
    private javax.swing.JTextField pelatis_txt1;
    private javax.swing.JTextField price_txt;
    private javax.swing.JButton pros8ikiadalaktikwn_btn;
    private javax.swing.JButton save_data;
    private javax.swing.JButton send_new_message_btn;
    private javax.swing.JMenuItem service_btn;
    private javax.swing.JPanel service_dash;
    private javax.swing.JTextArea service_notes_txt;
    private javax.swing.JTable service_table;
    private javax.swing.JTable servicehistory_table;
    private javax.swing.JTextField telephone_txt;
    private javax.swing.JTextField telephone_txt1;
    private javax.swing.JMenuItem trade_in_btn;
    private javax.swing.JPanel trade_in_dash;
    private javax.swing.JTable tradein_table;
    private javax.swing.JTextField year_txt;
    private javax.swing.JTextField year_txt1;
    // End of variables declaration//GEN-END:variables
}
